### PR TITLE
Feature/scatterplot

### PR DESCRIPTION
**Pull request by stellarluminary**
Hard coded implementation of a Rechart Scatterplot example. We still need to abstract the component into a data wrapper component and a rendering component.

### CODE REVIEW

**Comment by DavideDaniel** [comment]
This branch might need master merged into it.. there are way too many diffs in files I imagine you didn't intend to add changes..

**Comment by stellarluminary** [comment]
Since there are so many changes, I need to just overwrite my local master branch with the hackoregon master branch. I know you mentioned in class that we should avoid reset if we can help it, but is this a scenario where `git reset --hard hackoregon/master` is the only way to go?

I also tried deleting my local master branch and trying to replace it by fetching the hackoregon master, but that didn't work.

**Comment by stellarluminary** [comment]
Ok, I fixed my local master branch to match and track the hackoregon/component-library master branch, and made a new local feature/scatterplot branch with my Scatterplot code. It should be ok now.

**Review by DavideDaniel — CHANGES_REQUESTED** [review]
Both stories/index.js and script/index.js should not be removing the additions by others. If you could address those this looks nearly ready.

**Comment by stellarluminary** [comment]
Ok, I've pulled in the changes from the project repo master branch and added my scatterplot code. It should be ok now.

**Review by DavideDaniel — APPROVED** [review]

**Pull request merged**
