### PR TITLE
Davidabel

### PR DESCRIPTION
**Pull request by drabelpdx**
Here is my class assignment for a Leaflet component.

It adds leaflet, react-leaflet, jsdom and jsdom-global (for testing) modules.
It includes component, style, test and story files for Leaflet.

### CODE REVIEW

**Review by DavideDaniel — COMMENTED** [review]
I think you need to merge master into your branch.. you have a ton of commits in this pr that are already in the base branch.

**Review by DavideDaniel — COMMENTED** [review]
Good work figuring out a solution to the absent DOM.

**Comment by drabelpdx** [comment]
I've updated my branch to merge master to branch. I created my branch off master. Was I suppose to checkout the feature branch, then create my branch off that?

**Comment by drabelpdx** [comment]
You can close/remove this pull request. I've made another pull request after straightening out the branch issue. Thanks.

**Pull request closed without merging**
