### PR TITLE
Makes the nav links whiteish instead of blackish

### PR DESCRIPTION
**Pull request by DingoEatingFuzz**
Something I noticed when putting together a proof of architecture for the Housing team.

### CODE REVIEW

**Review by DavideDaniel — COMMENTED** [review]
@oovg any reason not to accept this?

**Comment by oovg** [comment]
Ultimately, it will depend on team primary-color for that Collection Hero area behind the nav links. If a lighter palette, then the blackish works better. If darker palette, then the whiteish works better. Would be rad if we could switch between based on the color value for maximum utility.

**Comment by oovg** [comment]
Maybe based on a brightness check similar to this? http://jsfiddle.net/2VTnZ/2/

**Comment by DavideDaniel** [comment]
The programmatic modification might not be an ideal solution. If we end up having common colors & css on the platform assigned by classname, then it might be easier to align the styling issues. Having said that, isn't the nav the same for everyone? All the projects are just routes inside the platform application.

**Review by DavideDaniel — APPROVED** [review]

**Pull request merged**
